apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak-pod
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
spec:
  selector:
    app: keycloak-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - name: management
      port: 15672
      targetPort: 15672
    - name: query
      port: 5672
      targetPort: 5672
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pga-service
spec:
  selector:
    app: articles-pga
  ports:
    - name: http
      port: 5050
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pg-articles-service
spec:
  selector:
    app: articles-pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pg-comment-service
spec:
  selector:
    app: comments-pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
