name: SonarCloud analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read
jobs:
  Backend-keycloak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend-keycloak
        uses: actions/checkout@v2
        with:
          path: ../Backend-keycloak

      - name: Set up JDK for Backend-keycloak
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and analyze Backend-keycloak with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ../Backend-keycloak
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=MyTech-Backend-keycloak \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.login=$SONAR_TOKEN

  backend-gateway-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend-gateway-client
        uses: actions/checkout@v2
        with:
          path: ../backend-gateway-client

      - name: Set up JDK for backend-gateway-client
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and analyze backend-gateway-client with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ../backend-gateway-client
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=mytech-backend-gateway-client \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.login=$SONAR_TOKEN

  backend-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend-resources
        uses: actions/checkout@v2
        with:
          path: ../backend-resources

      - name: Set up JDK for backend-resources
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and analyze backend-resources with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: ../backend-resources
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=mytech-backend-resources \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=$SONAR_ORGANIZATION_KEY \
            -Dsonar.login=$SONAR_TOKEN

